import: python:latest
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    TRIGGER_TOKEN: dc021b6d66845a124e8a7a1e2176c0

cache:
    paths:
        - .cache/pip
        - venv/

before_script:
    - python -V
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip setuptools wheel pylint pytest nuitka-setuptools Nuitka

stages:
    - Static Analysis
    - Test
    - Deploy

pylint:
    stage: Static Analysis
    script:
        - pylint --generate-rcfile > .pylintrc
        - pylint --rcfile=.pylintrc --confidence=INFERENCE_FAILURE src/

pytest-base:
    stage: Test
    script:
        - >  
          python3 src/flask.py -p test01
          if [ -d test01 ] && \
            [ -f test01/run.py ] && \
            [ -f test01/config.py ] && \
            [ -f test01/apps/__init__.py ] && \
            [ -f test01/apps/routes.py ] && \
            [ -f test01/apps/static/default.css ] && \
            [ -f test01/apps/templates/base.html ] && \
            [ -f test01/apps/templates/index.html ] && \
            [ -f test01/apps/templates/sample.html ]; then
              true
          else
              false
          fi
          cp -rv tests test01/

pytest-app-base-unit-testing:
    stage: Test
    script:
        - cd test01/; pytest -v

trigger_build:
    stage: Deploy
    script:
        - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/21472626/trigger/pipeline"

LinuxDeploy:
    stage: Deploy
    script:
        - nuitka3 --run --standalone \
          --remove-output \
          --output-dir=src/ \
          --show-progress \
          src/flask.py
        - tar -acv --directory=src flask.dist -f out.tgz
    tags:
        - deployLinux
    artifacts:
        paths:
            - ./out.tgz
